### ISSUE TITLE
Install firejail and sandbox default programs

### ISSUE THREAD

**Issue by KellerFuchs** [hashbang/shell-etc#86]
I think it would be a pretty good security improvements to provide users with firejail and run several things (like weechat or mutt) inside.
Note that user configuration (in ~/.config/firejail) always trumps system-wide config (in /etc/firejail).

This would ideally involve:
- [x] Improve [firejail](https://github.com/netblue30/firejail/)
  - [ ] [Privilege separation](https://github.com/netblue30/firejail/issues/510) (can come later)
  - [ ] Use capabilities rather than suid (can come later, since `CAP_SYS_ADMIN` is required AFAIK)
  - [x] Allow [enforcing use of `NO_NEW_PRIVS`](https://github.com/netblue30/firejail/pull/536) to make sure users don't exploit privileged binaries through firejail.
  - [x] [Add a mechanism for blacklisting/whitelisting features system-wide.](https://github.com/netblue30/firejail/issues/511).
  - [x] [Extend `restricted-network`](https://github.com/netblue30/firejail/pull/537) to apply to `--netfilter`.
- [x] [Blacklist unsafe features](https://github.com/hashbang/shell-etc/pull/93), enforce `NO_NEW_PRIVS`.
- [x] Install firejail, ~~possibly by building a backport.~~
- [x] [Provide a profile for mutt.](https://github.com/hashbang/dotfiles/issues/25)
  - [x] Use a non-sgid alternative for `sendmail`.
- [ ] Improve on the provided profile for weechat.
- Edit `dotfiles` to run things under firejail:
  - [x] `weechat`
  - [x] `mutt`
    ~~Alternatively, we can create symlinks from `/usr/local/bin/{mutt,weechat,...}` to `/usr/bin/firejail`, but I think that might be more confusing to users.~~

Pro:
- Protects users from vulnerabilities in sandboxed applications.  
  For instance, that would prevent exploitation of a vulnerability in `weechat` (or, more likely, in a script) to run `sudo hashbangctl`, access private keys and so on.
- Lets users sandbox arbitrary applications, unlike LSMs (like SELinux or AppArmor) which only allow `root` to define profiles.
- Encourage users to learn to use modern security features: `firejail` uses namespaces, capabilities and seccomp (mainly), yet stays fairly accessible and user-friendly.

Cons:
- A profile that is too restrictive can make sandboxed applications fail (by preventing access to a given ressource).
  We can have violations of the default profiles written to `syslog(3)` and mailed to us to be able to handle those issues quickly.
- A vulnerability in `firejail` itself may enable privilege escalation (by #! users), as it is a suid binary.  
  This seems pretty unlikely, however.

**Comment by KellerFuchs** [comment]
Ok, the (lengthy) description will come back once I'm less annoyed  :(

**Comment by KellerFuchs** [comment]
PS: That might be unclear in the description, but we can start providing `firejail` without sandboxing any application (you have to explicitely run `firejail weechat` to get it sandboxed) and thoroughly test the profiles first.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Would anyone have any issue with installing `firejail`?  That wouldn't make it automatically used anywhere (as I said, you have to explicitely run `firejail foo`), but it would let people (who want to) use it, test profiles and so on.

**Comment by AlissaSquared** [comment]
No issue.

On Wed, Apr 6, 2016 at 2:05 PM The Fox in the Shell <
notifications@github.com> wrote:

> @hashbang/administrators
> <https://github.com/orgs/hashbang/teams/administrators> Would anyone have
> any issue with installing firejail? That wouldn't make it automatically
> used anywhere (as I said, you have to explicitely run firejail foo), but
> it would let people (who want to) use it, test profiles and so on.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hashbang/shell-etc/issues/86#issuecomment-206515802>
>
-- 

Ryan Rion <ryan@hashbang.sh>
Programmer :: Scripter :: Designer :: Administrator
https://github.com/ChickenNuggers

**Comment by KellerFuchs** [comment]
Ok, let's install that.

**Comment by KellerFuchs** [comment]
```
       Ryan │ KellerFuchs: I'd suggest moving the sandboxing default programs to hashbang/dotfiles
       Ryan │ And then add 'install firejail' as an issue for shell-etc
KellerFuchs │ Ryan: Having the default profiles in dotfiles makes them hard to update if we ever find a bug in them, though
       Ryan │ Alright. System defaults, then.
```

**Comment by KellerFuchs** [comment]
Rolled back the installation of `firejail

**Comment by KellerFuchs** [comment]
@ChickenNuggers Thanks, I was too lazy to add the label to the project that early in the morning.

As soon as a new release of firejail is tagged (and available in Debian), we can install it again since it will support a config file letting us set which `firejail` features are available.

**Comment by KellerFuchs** [comment]
@hashbang/administrators OK, all the improvements we needed landed in upstream firejail, so we can start working on what we need next.

I'm opening a pull-request on `shell-etc` with the proposed firejail config, I will need people to review.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Providing a profile for `mutt` requires replacing our current `sendmail`: it relies on being a sgid binary to write new mails to the mail queue directly, which simply won't work with `NO_NEW_PRIVS`.

I suggest using `msmtp`:
- it's packaged in Debian;
- it is simple and can easily be configured system-wide (in `/etc`), with users being able to override settings;
- it can easily pin the fingerprint of `mail.hashbang.sh`;
- it supports GSSAPI for authenticating the users, when we finally get started with authenticating mail senders.

**Comment by dpflug** [comment]
I use msmtp at home. I'm a fan. :)

**Comment by KellerFuchs** [comment]
@dpflug I will take that as approval and just do it, then.

**Comment by KellerFuchs** [comment]
[firejail 0.9.40](https://tracker.debian.org/pkg/firejail) landed today in Debian unstable.
It should land in testing in a week, and we can move forward at that time.

@hashbang/administrators @hashbang/contributers In the meanwhile, we can get a profile for mutt ready.  That would help not losing momentum.

**Comment by KellerFuchs** [comment]
I merged in #93 and installed `firejail`.
I also have a basic profile for mutt, which I might send in a separate pull-request.

**Comment by KellerFuchs** [comment]
Doing some work now on `weechat.profile`.

**Comment by KellerFuchs** [comment]
We could actually enable firejail on weechat now: the profile is currently pretty basic, but better than nothing.

@hashbang/administrators Any thoughts?

**Comment by lrvick** [comment]
@KellerFuchs Fine with me.

**Comment by KellerFuchs** [comment]
@lrvick Done and tested.

**Comment by KellerFuchs** [comment]
Actually, now that weechat's firejail profile uses a homedir whitelist, it's not so basic anymore  :-)

I guess I can close this
